# config/inference/face2voice_tts.yaml
# Configuration for Face2Voice TTS inference

_target_: model.OpenVoiceTTS.Face2VoiceTTS

# Model checkpoints
face2voice_checkpoint: ${paths.checkpoint_dir}/face2voice/best_model.pth
openvoice_base: ${paths.checkpoint_dir}/checkpoints/checkpoints_v2/base_speakers/ses/en-default.pth
openvoice_converter: ${paths.checkpoint_dir}/checkpoints/checkpoints_v2/converter/checkpoint.pth

# Device
device: ${experiment.device}

# TTS settings
language: English  # English, Chinese
speed: 1.0  # Speaking speed multiplier

---
# config/inference_config.yaml
# Main inference configuration

defaults:
  - _self_
  - inference: face2voice_tts

# Paths
paths:
  root: ${hydra:runtime.cwd}
  checkpoint_dir: ${paths.root}/checkpoints
  test_images: ${paths.root}/test_images
  output_dir: ${paths.root}/outputs/inference

# Experiment
experiment:
  name: inference
  device: cuda
  seed: 42

# Inference settings
inference_mode:
  # single, batch, clone, compare
  mode: single
  
  # Single mode
  single:
    text: "Hello, this is a test of face-to-voice synthesis."
    face_image: ${paths.test_images}/person1.jpg
    output_path: ${paths.output_dir}/single_output.wav
  
  # Batch mode
  batch:
    texts_file: ${paths.root}/data/test_texts.txt
    faces_dir: ${paths.test_images}
    output_dir: ${paths.output_dir}/batch
  
  # Clone mode (one face, multiple texts)
  clone:
    face_image: ${paths.test_images}/person1.jpg
    texts:
      - "Hello, welcome to the demonstration."
      - "This is voice cloning from a face."
      - "The system generates consistent voice characteristics."
      - "Thank you for listening."
    output_dir: ${paths.output_dir}/cloned
  
  # Compare mode (same text, different faces)
  compare:
    text: "The quick brown fox jumps over the lazy dog."
    face_images:
      - ${paths.test_images}/person1.jpg
      - ${paths.test_images}/person2.jpg
      - ${paths.test_images}/person3.jpg
    output_dir: ${paths.output_dir}/comparison

# Post-processing
postprocess:
  normalize_audio: true
  trim_silence: true
  target_sample_rate: 24000

---
# config/inference/quick_demo.yaml
# Quick demo configuration

# @package _global_

inference_mode:
  mode: clone

  clone:
    face_image: test_images/demo_face.jpg
    texts:
      - "Welcome to Face-to-Voice TTS."
      - "This technology generates speech from facial images."
      - "Each face produces a unique voice."
    output_dir: outputs/quick_demo

---
# config/inference/batch_generation.yaml
# Batch generation configuration

# @package _global_

inference_mode:
  mode: batch
  
  batch:
    texts_file: data/batch_texts.txt
    faces_dir: data/batch_faces
    output_dir: outputs/batch_generation
    name_pattern: "audio_{:04d}.wav"

---
# config/inference/voice_comparison.yaml
# Voice comparison configuration

# @package _global_

inference_mode:
  mode: compare
  
  compare:
    text: "This is a test sentence for voice comparison."
    face_images:
      - test_images/face_male_1.jpg
      - test_images/face_male_2.jpg
      - test_images/face_female_1.jpg
      - test_images/face_female_2.jpg
    output_dir: outputs/voice_comparison
    generate_metadata: true  # Save comparison metadata